# Uncomment this line to define a global platform for your project

platform :ios, '8.0'
pod 'RCTMapboxGL', :path => 'node_modules/react-native-mapbox-gl/ios'

# Uncomment this line if you're using Swift
# use_frameworks!

target 'parking' do

end

target 'parkingTests' do

end

